### ISSUE TITLE
Add mro / rm jenkins library as global lib into jenkins

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#146]
and include
1.  workflow-cps-global-lib:2.13
1. junit:1.28
1. blueocean:1.17.0

into shipped plugins

**Comment by metmajer** [comment]
@clemensutschig and I have been elaborating on this and we wanted to provide the rationale behind this change.

**Why are we doing this?**

The Multi-Repo Orchestration (MRO) Jenkins pipeline and related shared library (both under active development) have to provide functionality that exceeds the capabilities made available by Jenkins' constrained Groovy Sandbox execution model (default). Examples of such functionality include:

- the parsing of YAML files including project- and component level configuration information to orchestrate multiple components into a live application using ordering and parallelization
- the easy access to data from a growing number of data sources, such as BitBucket, Confluence, and Jira to support automated document generation

While parsing YAML files is supported by the [Pipeline Utility Steps Plugin](https://jenkins.io/doc/pipeline/steps/pipeline-utility-steps/) in a Groovy Sandbox compatible manner, the possibilities with such plugins only go so far. The [HTTP Request Plugin](https://jenkins.io/doc/pipeline/steps/http_request/), for example, still doesn't support HTTP POST requests of *Content-Type: multipart/form-data* after being [a major priority since late 2018](https://issues.jenkins-ci.org/browse/JENKINS-54749?page=com.atlassian.jira.plugin.system.issuetabpanels%3Achangehistory-tabpanel).

I like to see our Jenkins shared libraries as sets of building blocks so that teams can build better pipelines easily through task composition (ref. *Pipeline SDK*). I argue that we'll be able to provide better experiences if we face less limitations in developing these experiences ourselves. Here's an example of a multipart request using `org.kong.Unirest`, which beautifully abstracts away the complexities of the underlying Apache HTTPClient (which would require ~ 80 LOC for the same result):

```
@Grab(group="com.konghq", module="unirest-java", version="2.3.08", classifier="standalone")

import kong.unirest.Unirest

def response = Unirest.post("${getBaseURI()}/service/rest/v1/components?repository={repository}")
    .routeParam("repository", repository)
    .basicAuth(this.username, this.password)            
    .field("raw.directory", directory)
    .field("raw.asset1", new ByteArrayInputStream(artifact), contentType)
    .field("raw.asset1.filename", name)
    .asString()

response.ifSuccess {
    if (response.getStatus() != 204) {
        throw new RuntimeException("Error: unable to store artifact. Nexus responded with code: ${response.getStatus()} and message: ${response.getBody()}")
    }
}

response.ifFailure {
    throw new RuntimeException("Error: unable to store artifact. Nexus responded with code: ${response.getStatus()} and message: ${response.getBody()}")
}
```

However, pulling in dependencies exceeds what's permitted by the Groovy Sandbox. Registering a shared library as a [Jenkins Global Shared Library](https://jenkins.io/doc/book/pipeline/shared-libraries/#global-shared-libraries) effectively puts a trust label onto this library, thereby removing said restrictions.

**What exactly are we doing?**

We are registering the MRO shared library as a [Jenkins Global Shared Library](https://jenkins.io/doc/book/pipeline/shared-libraries/#global-shared-libraries) to remove any restrictions otherwise applied by the Groovy Sandbox. There are two options of achieving this (both demand *Administrator privileges* and require the [Pipeline Shared Groovy Libraries Plugin](https://wiki.jenkins.io/display/JENKINS/Pipeline+Shared+Groovy+Libraries+Plugin)):

1) by registering the library under *Manage Jenkins » Configure System » Global Pipeline Libraries*
2) by registering the library in a Jenkins [post-installation script](https://wiki.jenkins.io/display/JENKINS/Post-initialization+script) in either `$JENKINS_HOME/init.groovy` or `$JENKINS_HOME/init.groovy.d/*.groovy`

Our pull request #148 uses approach 2) and registers the MRO shared library globally under the name `ods-mro-jenkins-shared-library`. This allows pipelines to access the library's jobs via `@Library('ods-mro-jenkins-shared-library') _`, as described [here](https://jenkins.io/doc/book/pipeline/shared-libraries/#using-libraries).

**What are the advantages / drawbacks to the current method?**

The biggest advantage is that our shared library code is unaffected of any Groovy Sandbox restrictions. As stated in Jenkins' documentation on [Jenkins Global Shared Libraries](https://jenkins.io/doc/book/pipeline/shared-libraries/#global-shared-libraries): *"These libraries are considered \"trusted:\" they can run any methods in Java, Groovy, Jenkins internal APIs, Jenkins plugins, or third-party libraries. This allows you to define libraries which encapsulate individually unsafe APIs in a higher-level wrapper safe for use from any Pipeline. Beware that anyone able to push commits to this SCM repository could obtain unlimited access to Jenkins."*

Naturally, such powers demand a greater degree of responsibility. Note though that these powers are limited to the code inside the shared library itself. A pipeline that uses a trusted shared library is still executed in a safe Groovy Sandbox context.

**How will users be able to customise this?**

A registration of a global shared library binds a library name to a repository, but not to a Git revision. Right now, the `rev` points to the library repository's `production` branch by default, but can be changed by the pipeline user to point to a random branch in the same repository. Example:

```
/* Using a version specifier, such as branch, tag, etc */
@Library('my-shared-library@1.0') _
```

**What else?**

Conceptually, a library managing repository orchestration should not deal with accessing data sources for automated document generation. Over time, these ownerships will be split up into dedicated libraries (potentially augment `ods-jenkins-shared-library` when it makes sense).

FYI @michaelsauter

**Comment by michaelsauter** [comment]
@metmajer Thanks for the detailed writedown 👌 You have my full support!
