### ISSUE TITLE
provide a one node okd for local installation

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-core#184]
Replace the _oc cluster up_ method with a _one note okd_ , by using the scripts from https://github.com/gshipley/installcentos

**Comment by michaelsauter** [comment]
@stefanlack Why?

**Comment by stefanlack** [comment]
@michaelsauter because the  _cluster up_ method is suffering from instability/ long start up times.

**Comment by michaelsauter** [comment]
OK, but the project says:

>  For a local only install, it is suggested that you use CDK or MiniShift instead of this repo. This install method is targeted for a single node cluster that has a long life.

Are we sure this is the right way to go? Do you use it extensively? Just interested since I've never seen that tool before ...

**Comment by tjaeschke** [comment]
During testing and working with local installations we have had the experience, that the cluster up didn't work as well as we expected. As @stefanlack mentioned there are stability and start up time issues and also problems, if you want to test changes in OKD locally. @rattermeyer had problems with testing OKD policies for ODS locally, _cluster up_ crashed without a message and additionally there is also this issue, that _cluster up_ doesn't provide the OKD version. Since we are also working on implementing an improved installation routine that not only covers a local installation, this seems to be a feasible way.

**Comment by metmajer** [comment]
Very much looking forward to a local installation! Let me know if I can help with beta testing on a Mac.

**Comment by michaelsauter** [comment]
Closing as there is a dev env box now, and the PR associated with this issue is closed.
