### ISSUE TITLE
Project creation pipeline fails with unknown host http

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-core#258]
**Describe the bug**
If you create a project creation pipeline the checkout of ods-configuration fails, because the schme is doubled (see screenshot)

**To Reproduce**
Create a project via the provisioning app with current master

**Expected behavior**
Pipeline is created and ods-configuration can be checked out without a doubled scheme.

**Screenshots**
![image](https://user-images.githubusercontent.com/24410591/69529801-40235580-0f71-11ea-902f-4fb2c9b0870c.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack master

**Additional context**
It seems that the ENV variable BITBUCKET_HOST is overwritten by the project creation script, which has a scheme and becuase of this the scheme is added twice.

**Comment by michaelsauter** [comment]
@tjaeschke Are you sure that is not due to a misconfiguration? See https://github.com/opendevstack/ods-provisioning-app/blob/master/ocp-config/prov-cd/Tailorfile#L3 and https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L83. To me it looks like https://github.com/opendevstack/ods-core/blob/master/create-projects/Jenkinsfile#L12 would be without a scheme, and then https://github.com/opendevstack/ods-core/blob/master/create-projects/Jenkinsfile#L44-L45 adds the scheme.

**Comment by michaelsauter** [comment]
That said, I would love to introduce a `BITBUCKET_URL` config which has the scheme in it so that we do not need those hacks.

**Comment by tjaeschke** [comment]
The issue seems to be, that the `ENV` variable is overwritten from the option that is set by the provision app in https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java#L167

Here the bitbucket host is configured to be the bitbucket uri, that has a scheme.

Jenkins `ENV` variable is set without host, like configured in the templates.

I agree that we should switch to `BITBUCKET_URL`.

**Comment by michaelsauter** [comment]
@tjaeschke Then I'd say the bug here is that the provisioning app sets that environment variable. It should NOT do that in my eyes Agree?

FYI @kiwo

**Comment by tjaeschke** [comment]
@michaelsauter Agree. Got to that point, too. I will remove it and test the project creation without it.
