### ISSUE TITLE
Rethink ocp-config Location- in order to only have one configuration Repository 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#3]
Suppose i want to use ods as is- today i need to Clone all repos to sie tailor for Installation. I think it would be wise to move all ocp config into ods-configuration-sample- so we have one place to clone and install..  

Thoughts?

**Comment by michaelsauter** [comment]
Interesting thought!

I think there are two aspects for this:

* What do we want the users to clone?
* Where is the OCP config best located?

I thought a little about the first question, and I am leaning towards suggesting or even requiring to clone all repos. There are two reasons for this:

1. Once users have cloned all repos, the update procedure is quite nice: Merge desired tag into master, and then merge master via PR into production. Remember that ODS hardcodes to use the production branch at the moment. If users just follow github.com/opendevstack directly, they will receive updates automatically, which have a high potential of breaking their environment. By asking the users to clone all repos, they also have better control of when to update, and an easier way to review changes.

2. By cloning all repos at the beginning, users are immediately setup to contribute to ODS. The smaller the hurdle is to contribute back, the better.

Because of those reasons, I think we should have the user clone all repos. 

If we agree on this, your question is more centered around the second point - where should OCP config live. I see why moving everything into one place is attractive from an admin point of view, but on the other hand co-location with where the config relates to is quite powerful and I'm not (yet) ready to let go of this. I have to think more about this one. @stitakis @rattermeyer Thoughts?

**Comment by michaelsauter** [comment]
We have settled both questions:

* Users should clone all repos
* Single repo with all config
