### ISSUE TITLE
Solve self-provisioner permissions mystery

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#380]
This is a follow-up from https://github.com/opendevstack/ods-project-quickstarters/issues/314.

ODS has the following requirements:

1. The `jenkins` serviceaccount in the `prov-cd` project needs to be able to create new projects, as it is responsible to create the `foo-dev`, `foo-test`, `foo-cd` namespaces.
2. The `jenkins` serviceaccount in each `*-cd` project needs to be able to create new projects when the auto-clone feature is used.

Observing the situation in different clusters:

* On a RedHat Dedicated cluster, both use-cases work, without granting `self-provisioner` explicitly anywhere in ODS. The rights must come from somewhere else. Potentially https://access.redhat.com/solutions/2988521 has been applied? I will follow this up to see if it is the case. Still, it would not explain how projects created through `prov-cd:jenkins` can make use of the auto-clone feature (2). There must be some other secret sauce that I do not know yet ...
* In the tests running in a temporary cluster using `oc cluster up`, we have now realised that the rights to do this are actually applied outside of ODS code - they are applied just in the tests. See https://github.com/opendevstack/ods-core/blob/f96c2ad2b25ac808f33d6b6b6f53dbbf5c7d8043/tests/scripts/recreate-test-infrastructure.sh#L12-L14 and https://github.com/opendevstack/ods-core/blob/f96c2ad2b25ac808f33d6b6b6f53dbbf5c7d8043/tests/scripts/recreate-test-infrastructure.sh#L65 The tests do not cover the auto-clone feature yet so it is unclear if auto cloning would work given those settings (in theory they should not ...). As a follow-up, the tests should NOT apply those changes in test-code, the commands need to move to ODS setup-code.
* In an onprem cluster updated from ODS 1.2 to 2.0, both use cases do not work without granting rights like it is done in the tests.

FYI @clemensutschig @rattermeyer @hugowschneider @gerardcl @henrjk @stitakis @stefanlack 

Please add any piece of information you have that I have not yet written down. I am slowly starting to see the whole picture and I do not want to miss something.

**Comment by gerardcl** [comment]
I confirm all the above, and also to add that a response from a RH ticket confirmed they do not provide different defaults/configurations related to the self-provisioner cluster-role. So this might potentially be a cluster admin config to be applyed as an "ODS cluster admin". 

Next step would be to confirm possibility to keep the autocloning feature everywhere without manual config need (so to provide self-provisioner role at project creation to the project jenkins cd user), updating [here](https://github.com/opendevstack/ods-core/blob/master/create-projects/create-projects.sh) and playing with https://access.redhat.com/solutions/2988521 (see "root cause" section)

**Comment by michaelsauter** [comment]
After reviewing the mentioned RH ticket, we now know one way to make auto-cloning work automatically for all serviceaccounts:
```
oc adm policy add-cluster-role-to-group self-provisioner system:serviceaccounts
```

At least now we have a clear picture. As a next step, I propose we document which permissions are required for which feature, and then think about the possible code changes ...
