### ISSUE TITLE
Automated local setup of ODS dev environment on remote workstation

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/ods-core#398]
**Is your feature request related to a problem? Please describe.**
Provide scripts / automation to facilitate a quick and consistent setup of an ODS development environment on a local VM (non-exclusive) or AWS VM outside of the BI network to support onboarding and ongoing development.

**Describe the solution you'd like**
A set of script that can be executed on a fresh VM (Ubuntu 16.04 LTS for starters, maybe more at a later time) to setup an ODS development environment outside of the BI network, providing all required components like an OpenShift cluster and the Atlassian tool suite.

**Describe alternatives you've considered**
For personnel who do not have access to BI infrastructure (notebook / desktop, access to BI internal network) there do not appear to be alternatives to get started developing ODS.

**Additional context**

**Comment by michaelsauter** [comment]
@stefanlack @tjaeschke How does that relate to the local setup you are using?

**Comment by tjaeschke** [comment]
At the moment I'm working in this,

**Comment by michaelsauter** [comment]
@tjaeschke Cool. Could you align with @metmajer / @georgfedermann to ensure that we are on the same page regarding the goals and approach to this?

Also, since this is a bigger topic, maybe you can add it to https://github.com/opendevstack/PMC/wiki/ODS-3.0-Work-Packages and describe in a few words what you are doing and that you are doing it so that we have some transparency over the "big picture" work packages that are worked on for 3.0 ...

**Comment by tjaeschke** [comment]
@michaelsauter Sure.

**Comment by georgfedermann** [comment]
@tjaeschke that sounds great. Could we align? I'll be happy to contribute and do testing.
I've created a script to setup ODS on a fresh Ubuntu 16.04 VM, based on the github workflow continuous-integration-workflow.yml and other scripts, for which I was going to create a PR next.
Would that help you? Are you working on something similar here?

**Comment by metmajer** [comment]
The aim here is to create a slim development and demo environment with OpenShift and ODS inside a single VM to support contributors in getting started quickly. The solution we have started working on already, and which is largely based on @hugowschneider's Travis integration came out of the pain of having people wait too long to become active. Integrating it into a company network will not be tackled initially (focus currently is on GitHub contributions over everything else in the first run).

**Comment by tjaeschke** [comment]
@georgfedermann Sure, I like the approach. As soon as I can contribute something to GithUb, I will get in touch with you.

**Comment by tjaeschke** [comment]
A general question. What is the problem to utilize ansible or to adapt the current local setup scripts and change them the way you need them?

From our experience you will get problems with cluster up, since it is more stable than a Minishift, but still has issues with not providing the running OpenShift version, missing deletion of secret mounts, issues with running in docker errors, leading to a corrupted cluster, that has to be reinstalled. 

Adding @rattermeyer

**Comment by rattermeyer** [comment]
To bring another thing onto the plate: I would like to see for development setup the replacement of Bitbucket with gitea. For local work, you do not need confluence and jira, and webhooks can also be created for gitea.

**Comment by georgfedermann** [comment]
> A general question. What is the problem to utilize ansible or to adapt the current local setup scripts and change them the way you need them?

Ansible might well be the technology of choice in the end. For the moment we are just looking for the least complex technology footprint possible to achieve the goal of getting a working development environment to build and run ODS locally.

> From our experience you will get problems with cluster up, since it is more stable than a Minishift, but still has issues with not providing the running OpenShift version, missing deletion of secret mounts, issues with running in docker errors, leading to a corrupted cluster, that has to be reinstalled.

OK, interesting. Do I get you right that you suggest using a Minishift installation instead of providing OpenShift using oc cluster up in a development environment (as opposed to using oc cluster up e.g. for running automated tests)? What are your experiences with Minishift in your local development environment? How do you get a working ODS seutp on Minishift? Thanks for your input.

**Comment by tjaeschke** [comment]
We used Minishift in the versions prior to 1.x and there had been a lot of problems with underlying windows hosts. So we shifted to cluster up and experienced the problems mentioned above.

At the moment we are working on implementing a little real one node cluster in a vm to get a easier and stable local OpenShift.

**Comment by stefanlack** [comment]
see https://github.com/opendevstack/ods-core/pull/185

**Comment by metmajer** [comment]
What we want to achieve is a development environment that runs ODS integration and acceptance tests using the same foundations established by @hugowschneider. Therefore, the local installation is not an option.

- Jira and Bitbucket are assumed by the Release Manager, but I'd welcome `gitea` if it's a straight-forward replacement. This would need to take Webhooks support into account though.
- The discussion `oc cluster` vs. `minishift` isn't heading anywhere since both will be useless when we switch to OpenShift 4.

@tjaeschke @stefanlack @rattermeyer please support Georg on his way. He will have questions regarding how to set up the provisioning app, etc. Thanks a lot in advance!

**Comment by michaelsauter** [comment]
FWIW, OCP 4 can be installed locally via https://github.com/code-ready/crc, which seems to be OpenShift's tool of choice. We should come up with a solution for OCP 3 that is somewhat "compatible" with CRC so that it is an easy swap.

**Comment by metmajer** [comment]
@michaelsauter can you see those compatibilities somewhere?

**Comment by michaelsauter** [comment]
Sorry, I think we misunderstood each other. I just wanted to point out that it would be good to make the local setup in such a way that it would also work if you'd start a OCP 4 cluster via CRC. I think CRC and "oc cluster up" are similar from its approach ... not sure how different minishift / node setup is from that.

**Comment by metmajer** [comment]
No, that was exactly what I meant. Cheers @michaelsauter
