### ISSUE TITLE
CNES report plugin in base slave incompatible with ods-core SQ version 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#419]
**Describe the bug**
the shipped version in ODS 2.0 of CNES report - is 2.0x .. yet it only supports SQ up to 7.x and not 8 (which is shipped with ODS core)

https://github.com/opendevstack/ods-core/blob/master/jenkins/slave-base/Dockerfile.rhel7#L9
``` 
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true

SonarQube URL: .....

SonarQube online: true

Detected SonarQube version: 8.2.0

[ERROR] SonarQube instance is not supported by cnesreport.

script returned exit code 255 
``` 

**Affected version (please complete the following information):**
 - OpenDevStack [e.g. 2.x]

**Comment by clemensutschig** [comment]
https://github.com/lequal/sonar-cnes-report/releases/tag/3.1.0

**Comment by metmajer** [comment]
@segator we have already done the change together internally. Can you provide the adaptations here?

**Comment by stefanlack** [comment]
See also https://github.com/lequal/sonar-cnes-report/pull/105

**Comment by michaelsauter** [comment]
Hmm. ODS does not actually ship a SQ version: https://github.com/opendevstack/ods-core/blob/master/sonarqube/Dockerfile#L28.

So far, ODS has only been tested up to SonarQube 7.9, and I would recommend staying with that rather than going to 8.2.

Therefore, the issue here is actually that ODS does not support SQ 8+ :) We should note somewhere what the tested / allowed versions of SQ are.

**Comment by stefanlack** [comment]
We have already migrated to sonar qube 8 at our site. I could provide pull requests for required changes. Since we do not use cnes report, migration to sonar qube was possible.

**Comment by clemensutschig** [comment]
3.10 works super nicely .. PR to follow
