### ISSUE TITLE
Move opendevstack from current "global" CD OCP namespace to opendevstack/ods namespace

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#493]
I gave this some thought - and the longer I think about it  - the more I believe we should do this ..

1. it gives clarity
1. for a user during upgrade there is no difference between changing an `image ref` in the a components' `jenkinsFile` - or the entire path of the image used there (from `cd/....:2.x` to `opendevstack/....3.x`) and similar for jenkins / webhook / docgen dc 
1. We could flip all project specific service account' pull rights to one rolebinding `image puller system:authenticated` so no impact for a user on that front
1. In case we ship published images, we have to create image streams pointing to those published images anyway in the global namespace, no matter if it's in the current 'CD' or the new `opendevstack` one.. 

On our side the change is massive (but the outcome is really nice, as it could be configurable via ods-configuration env properties) .. so people could actually have multiple namespaces, including `-dev/test` ones..

Changes needed:
1. quickstarters (jenkins slave references / master imagestream)
1. ods-core (all master image streams, scripts, role bindings for pull rights)
1. prov cd (jenkins image)
1. mro / doc gen service (imagestreams, jenkins slave images)

@michaelsauter @metmajer @gerardcl @sino92  - thoughts?

**Comment by michaelsauter** [comment]
Awesome. I'm totally with you to rename the `cd` namespace. I always thought the name is confusing (as it is to similar with `*-cd` namespaces). As a new name, I'd suggest `ods` as that is shorter, which makes it a better fit for URLs I think. But - best case we make this configurable and just default to `ods` or `opendevstack` :)

3.0 is a great time to do that change as prov-app, jenkins and webhook proxy will be moved into the central namespace, so people need to update URLs anyway.

Apart from that, I do not think the update for the user is that hard:
- change image stream pointers
- change URL of SonarQube and Nexus

I believe your issue is actually two-fold:

1. Rename central namespace
2. Allow multiple central namespaces

I would vote to go forward with (1) for 3.0. I also love (2), but I think we could support this in a more general fashion. If all the scripts are parameterised, then users can instantiate central namespaces with whatever name they want. They could have `-dev`/`-test`, or namespaces with versions in them. So my suggestion would be to parameterise everything, and once that is in place, see what we want to offer - or if we say: if you want it, go ahead and do it but there is no official support.

FYI @oalyman

**Comment by michaelsauter** [comment]
FYI Image pulling is already allowed for `system:authenticated` in https://github.com/opendevstack/ods-core/blob/master/ods-setup/setup-ods-project.sh#L47.

**Comment by clemensutschig** [comment]
the big question, do we then create a `-dev / - test / -prod` namespace as well - to allow building of non BC driven builds (prov app / doc gen service)

**Comment by michaelsauter** [comment]
I think I would still build prov-app and doc-gen in their own namespaces. Any central namespace should pull images either from a local namespace, or from Docker Hub. So that a central `ods-test` actually reflects the "production" setup.

**Comment by stitakis** [comment]
Not sure about doc-gen, but after the completion of the work of deploying ProvApp to cd namespace as docker image, I would vote to move the ProvApp deployment script (that provision prov-cd, prov-dev and prov-test) to the ProvApp repository.

**Comment by clemensutschig** [comment]
ok lets spell it out .. below is my understanding of what it would like

`opendevstack`
1. Jenkins Master (image and instance)
1. Jenkins Slaves (images)
1. Provison Application (image and isntance)
1. Webhook Proxy (image and instance)
1. Document-Generation Service (image)

`ODS Provision App - ods-provision-app`
1. `-dev / -test / -prod`

`ODS Document Generation - ods-doc-gen-svc`
1. `-dev / -test / -prod`

yes?

**Comment by stitakis** [comment]
yes, looks good to me.

**Comment by michaelsauter** [comment]
Looks good, with the following questions / exceptions:

Point 6: Shared lib -> There is no BC/pipeline, right? Or what are you referring to? The shared lib is purely a Git reference.

For Prov App / Doc Gen, I would keep the current namespace setup. Below using the prov-app as an example, but the same applies for DocGen:

My view would be to have `prov-cd`, `prov-dev`, `prov-test`.

In my eyes, there is no `prov-prod`, because the production instance is located in the central `opendevstack` namespace. Also, I think having `-cd`/`-dev`/`-test` is a nice setup as it resembles a typical project setup.

Whether to name them (using the `-dev` namespace as an example) `prov-dev`, or `prov-app-dev`, or `ods-prov-app-dev` or `ods-provisioning-app-dev` ... I don't really mind as for me this is pure development :)

**Comment by clemensutschig** [comment]
> Point 6: Shared lib -> There is no BC/pipeline, right? Or what are you referring to? The shared lib is purely a Git reference.

it does (we seed a pipeline for it to test) and once the jira plugin comes it will contain a build pipeline as well (jar)

**Comment by michaelsauter** [comment]
@clemensutschig Could the Jira plugin be published (like the prov app)? If so, that would be great.

**Comment by clemensutschig** [comment]
@michaelsauter  - sure we can do so ... but nonetheless .. would we then create one more project for the plugin `ods-jira-plugin-cd`

**Comment by clemensutschig** [comment]
Ok cool - so I guess this is decided .. I vouch that we do this shortly before the release in one shot, across all ODS components, ok?

**Comment by clemensutschig** [comment]
`opendevstack`
1. Jenkins Master (bc, image and instance)
1. Jenkins Slaves (bc, images)
1. Provison Application (image and instance)
1. Webhook Proxy (bc, image and instance)
1. Document-Generation Service (image)
1. Sonarqube (bc / image / instance)
1. Nexus (bc / image / instance)

and the process for complex build images of ODS is to *import image from github* or *build yourself for the below ones*

`ODS Provision App - ods-provision-app`
1. `-cd / -dev / -test`
1. bc / image / cm ... & dc

`ODS Document Generation - ods-doc-gen-svc`
1. `-cd / -dev / -test`
1. bc / image

`ODS Jira Plugin - ods-jira-project-plugin`
1. `-cd` and upload to nexus?


`ODS Jenkins Shared Library - ods-jenkins-shared-lib`
1. `-cd`

**Comment by clemensutschig** [comment]
@oalyman and me gave them dev environments some thoughts ... current state of the union:

1. user provisions a new project (whichever name wanted)
1. user provisions a *NEW* quickstarter (ODS Development Provision App)
1.1 this creates the repo
1.2 adds github as remote and fetches
1.3 creates a branch from github master
1.4 pushes all that upstream into the bb repo

**Comment by clemensutschig** [comment]
see opendevstack/ods-jenkins-shared-library#266, opendevstack/ods-jenkins-shared-library#267, opendevstack/ods-jenkins-shared-library#268

**Comment by michaelsauter** [comment]
Two quick notes:

- Deploy using Tailor is anyway on my list for 3.0. I believe this is not related to MRO actually - even if you don't use the MRO, you should be able to deploy using your infrastructure-as-code approach
- I realised that the suggested approach has the downside of maintaining the ocp-config of the prov-app in two locations (`ods-core` for consumers, `ods-provisioning-app` for developers). I would love to take a little more time to think about this before we commit to early on a specific approach

**Comment by clemensutschig** [comment]
@michaelsauter  - re (2) .. this is what @oalyman is currently working on.

**Comment by stitakis** [comment]
@michaelsauter I think it is fine that the ocp-config of the prov-app is in 2 locations. The repo `ods-core` should include the configuration for consumers. The repo `ods-provisioning-app` should include the ocp-config for developer that want to deploy in openshift.
