### ISSUE TITLE
Add Travis tests for webhook proxy

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-core#64]
Similar to https://github.com/opendevstack/tailor/blob/master/.travis.yml.

**Comment by henrjk** [comment]
It appears Travis does not directly support having multiple 'packages' in a single repository.

It supports a (single) package in a subdirectory: See  https://docs.travis-ci.com/user/languages/r/#package-in-a-subdirectory.

Since the web hook is the first Travis package we could get away with just that for now.

It feels cleaner to somehow support multiple travis packages, for example if in the future a jvm based package is added. For example an approach is described at [How to configure TravisCI free for multi project repos](https://medium.com/google-developers/hacks-i-did-to-use-travis-ci-with-firebase-ios-quickstarts-da67c4986f29).

Another choice is to create a dedicated git repository for the webhook. But I am not sure whether this makes sense at all.

Any thoughts on how to proceed are welcome!

**Comment by michaelsauter** [comment]
@henrjk I see .... that's bad. I'm strongly against moving the webhook out into a separate repo, we already have too many repos (maintenance and release management is more difficult with more repos).

One other solution that comes to mind is that we could run the tests in Docker containers ... I figured out that this is possible in Travis, see https://github.com/opendevstack/tailor/pull/84. One could run the tests for each package in a Docker container for that language.

**Comment by henrjk** [comment]
This looks a lot better. I will take a stab at that!

**Comment by henrjk** [comment]
# Notes about PR #68 

It eventually registered with me that the matrix feature of travis can be used to build various different packages in one project. See answer https://stackoverflow.com/a/44054333 of
https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages for more details.

Because of this I did not pursue using docker and openshift as is used in opendevstack/tailor#84.

**Comment by clemensutschig** [comment]
@henrjk  - isnt that done with the merge now? #68

**Comment by michaelsauter** [comment]
Yes, this addresses #68. Forgot to close.
