### ISSUE TITLE
create project jenkinsfile hardcodes branch to master

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-core#799]
create project hardcodes branch to master on ods-configuration,
as we have multi cluster installation we have diferents branches in ods-configuration per cluster, we need a way to indicate to the system which branch.

I also afraid this happens on all the jobs that are trying to clone ods-configuration.
Ideally we should put a new parameter in ods-core.env lilke ```ODS_CONFIGURATION_BRANCH``` and this should be injected as env var to jenkins then jenkinsfiles will be save to use ```${env.ODS_CONFIGURATION_BRANCH}```

**Comment by clemensutschig** [comment]
This is per Design. A cautious Choice... as you cannot protect access to Branches for different users in bitbucket

**Comment by clemensutschig** [comment]
You are free to make the Change locally..  the Design is to have multiple ods bitbucket projects

**Comment by michaelsauter** [comment]
Correct, one ODS installation = one Bitbucket Project = one OpenShift namespace. Avoids permissions issues and accidental mistakes.

**Comment by martsec** [comment]
Hi @clemensutschig @michaelsauter I can't understand your opposition to this. Since there is one Platforms team for all the clusters we have, it makes sense to handle the configuration that way. They only difference between installations will be limited to one repo branch, making it easier to minimize mistakes and compare cluster config. I don't think it makes sense is to maintain 3-7 different ODS codebases, with all the issues associated to the potential human errors this entails. 

And of course, by default it can be kept as it is, but giving the option to have it another way. If different teams need to support different cluster installations, of course then the solution would be to have different projects. But we are not here.
